# -*- coding: utf-8 -*-
"""logistic recursion

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qY8newnkkU9eJyhXklgeiebj-k4jaKww
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from  sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")
print(df.head())

df.drop(['Name', 'Ticket', 'Cabin'], axis=1, inplace=True)

# check for missing values before handling
print("Missing values before handling:\n",df.isnull().sum())

  # Handle missing values
if'Age' in df.columns:
  df['Age'].fillna(df['Age'].median(),inplace=True)
if'Embarked' in df.columns:
  df['Embarked'].fillna(df['Embarked'].mode()[0],inplace=True)
print("Missing values after handling:\n",df.isnull().sum())

df['Sex']=LabelEncoder().fit_transform(df['Sex'])
df['Embarked']=LabelEncoder().fit_transform(df['Embarked'])

numeric_df=df.select_dtypes(include=['float64','int64'])
numeric_df.fillna(numeric_df.median(),inplace=True)
plt.figure(figsize=(10,6))
sns.heatmap(numeric_df.corr(),annot=True,cmap='coolwarm',fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

x = df.drop("Survived" , axis=1)
y = df["Survived"]

import pandas as pd

# Select revelant numeric features for scaling  (you can customize this)
features = ['Age', 'Fare', 'Pclass', 'SibSp', 'Parch']
x = df[features]

# Handle missing values (if any)
x = x.fillna(x.median())

# Standard Scaling
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

# Convert back to DataFrame (optional)
x_scaled_df = pd.DataFrame(x_scaled, columns=features)

# View result
print(x_scaled_df.head())

x_train, x_test, y_train, y_test=train_test_split(x_scaled, y, test_size=0.2, random_state=42)

model = LogisticRegression()
 model.fit(x_train, y_train)

y_pred = model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Model Accuracy: {accuracy:.2f}")
print("Classification Report:\n", classification_report(y_test, y_pred))

